on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */3 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          USER_NAME: "meihanai"
          USER_EMAIL: "131862741+meihanai@users.noreply.github.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
